export const STUDENTS_DATA = [
//     {
//         name: "Michael Martins",
//         email: "michaelmartins1136@gmail.com",
//         phone: "8022740397",
//         dateOfBirth: "2008-09-05",
//         gender: "M",
//         grade: "",
//         parentName: "Mrs Roseline Eno Michael",
//         parentEmail: "michealroseline001@gmail.com",
//         schoolName: "",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Adewumi Princess Boluwatigba",
//         email: "adewumivine11@gmail.com",
//         phone: "8063636254",
//         dateOfBirth: "22/04/2011",
//         gender: "F",
//         grade: "SS2",
//         parentName: "Adewumi Ayoyimika Tosin",
//         parentEmail: "at_adewunmi@yahoo.com",
//         schoolName: "Methodist Girls High School Yaba Lagos",
//         headOfSchoolEmail: "mghs_yaba@yahoo.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Ekeocha Shalom Udochukwu",
//         email: "officialbafffala01@gmail.com",
//         phone: "8029511799",
//         dateOfBirth: "15/02/2009",
//         gender: "M",
//         grade: "",
//         parentName: "Onoyona-Ekeocha Isoken",
//         parentEmail: "ekeocha80ky@gmail.com",
//         schoolName: "",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Abdulazeez  Halimah Kayinsola",
//         email: "halimahkanyinsola42@gmail.com",
//         phone: "8025727189",
//         dateOfBirth: "29/04/2009",
//         gender: "F",
//         grade: "SSS",
//         parentName: "Azeez Afeez Babatunde",
//         parentEmail: "azeezafeez36@gmail.com",
//         schoolName: "Ilasan Senior Secondary School",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Olanrewaju Muheez Olawale",
//         email: "olanrewajumuiz202@gmail.com",
//         phone: "",
//         dateOfBirth: "2005-10-10 00:00:00",
//         gender: "M",
//         grade: "SS3",
//         parentName: "",
//         parentEmail: "",
//         schoolName: "The legends College",
//         headOfSchoolEmail: "ayangbolanyandeji25@gmail.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Laaro Musa Olayinka",
//         email: "laaromoshood0@gmail.com",
//         phone: "8034510422",
//         dateOfBirth: "14/11/2009",
//         gender: "M",
//         grade: "",
//         parentName: "Laaro Moshood Olatunji",
//         parentEmail: "musalaaro11@gmail.com",
//         schoolName: "",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Mutiu Deborah Kikelomo",
//         email: "marydami80@gmail.com",
//         phone: "7067495246",
//         dateOfBirth: "16/12/2012",
//         gender: "F",
//         grade: "JSS3",
//         parentName: "Mutiu Abosede Oluwadamilila",
//         parentEmail: "anthonymary216@gmail.com",
//         schoolName: "Hephzibah College",
//         headOfSchoolEmail: "hephzibahcollege@yahoo.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Laaro Musa Olayinka",
//         email: "musalaaro11@gmail.com",
//         phone: "8034510422",
//         dateOfBirth: "14/11/2009",
//         gender: "M",
//         grade: "",
//         parentName: "Laaro Moshood Olatunji",
//         parentEmail: "musalaaro11@gmail.com",
//         schoolName: "",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Ezeani Ebuka David",
//         email: "blessbaby40@gmail.com",
//         phone: "8023038538",
//         dateOfBirth: "2010-09-01 00:00:00",
//         gender: "F",
//         grade: "SS1",
//         parentName: "Mrs Blessing Ezeani",
//         parentEmail: "blessworld2004@gmail.com",
//         schoolName: "Shining Lord's College",
//         headOfSchoolEmail: "shininglordscollege25@gmail.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Appiah Emmanuel Godwin",
//         email: "emmana2385@gmail.com",
//         phone: "",
//         dateOfBirth: "13/02/2010",
//         gender: "M",
//         grade: "SS2",
//         parentName: "",
//         parentEmail: "",
//         schoolName: "The legends College",
//         headOfSchoolEmail: "atomicboy2006@yahoo.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
    // {
    //     name: "Oyebamiji Tobi Timileyin",
    //     email: "tobioyebams48@gmail.com",
    //     phone: "",
    //     dateOfBirth: "2009-04-05",
    //     gender: "M",
    //     grade: "SS1",
    //     parentName: "",
    //     parentEmail: "",
    //     schoolName: "The legends College",
    //     headOfSchoolEmail: "ayangbolanyandeji25@gmail.com",
    //     consentG: 'y',
    //     consentH: 'y',
    //     organizationId: "685ec1191008ea7cff78dbc8"

    // },
//     {
//         name: "Olanrewaju Muheez Olawale",
//         email: "olanrewajumuiz202@gmail.com",
//         phone: "",
//         dateOfBirth: "2005-10-10 00:00:00",
//         gender: "M",
//         grade: "SS3",
//         parentName: "",
//         parentEmail: "",
//         schoolName: "The legends College",
//         headOfSchoolEmail: "ayangbolanyandeji25@gmail.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Shomorin Temitope Peace",
//         email: "shomorintemitope18@gmail.com",
//         phone: "8000000000",
//         dateOfBirth: "18/07/2009",
//         gender: "F",
//         grade: "SS3",
//         parentName: "Shomorin Temitope Peace",
//         parentEmail: "shomorintemitope18@gmail.com",
//         schoolName: "Shomorin Temitope Peace School",
//         headOfSchoolEmail: "Shomorin Temitope Peace",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Abdulazeez  Halimah Kayinsola",
//         email: "halimahkanyinsola42@gmail.com",
//         phone: "8025727189",
//         dateOfBirth: "29/04/2009",
//         gender: "F",
//         grade: "SSS",
//         parentName: "Azeez Afeez Babatunde",
//         parentEmail: "azeezafeez36@gmail.com",
//         schoolName: "Ilasan Senior Secondary School",
//         headOfSchoolEmail: "",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },
//     {
//         name: "Abubakar Damilare Usman",
//         email: "usman.me1703@gmail.com",
//         phone: "8000000000",
//         dateOfBirth: "18/07/2009",
//         gender: "F",
//         grade: "SS3",
//         parentName: "usman.me1703@gmail.com",
//         parentEmail: "usman.me1703@gmail.com",
//         schoolName: "usman.me1703@gmail.com School",
//         headOfSchoolEmail: "usman.me1703@gmail.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"
//     },
//     {
//         name: "Owolola Olamide Gracious",
//         email: "owololaolamide489@gmail.com",
//         phone: "8061395897",
//         dateOfBirth: "29/12/2008",
//         gender: "M",
//         grade: "SS2",
//         parentName: "Mrs Modupe Abigail",
//         parentEmail: "mamadee4shalom@gmail.com",
//         schoolName: "Royitola High School",
//         headOfSchoolEmail: "royitolaschool@yahoo.com",
//         consentG: 'y',
//         consentH: 'y',
//         organizationId: "685ec1191008ea7cff78dbc8"

//     },

    {
        name: "Yusuf Ibrahim Akanji",
        email: "yusufibrahimakanji741@gmail.com",
        phone: "",
        dateOfBirth: "2001-04-05",
        gender: "M",
        grade: "UNI",
        parentName: "",
        parentEmail: "",
        schoolName: "Osun State",
        headOfSchoolEmail: "yusufibrahimakanji741@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
];