export const STUDENTS_DATA = [
    {
        name: "Ekeocha Shalom Udochukwu",
        email: "officialbaffala01@gmail.com",
        phone: "8029511799",
        dateOfBirth: "15/02/2009",
        gender: "M",
        grade: "",
        parentName: "Onoyona-Ekeocha Isoken",
        parentEmail: "ekeocha80ky@gmail.com",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"
    },
    {
        name: "Bakare Esther Iyanuoluwa",
        email: "",
        phone: "8083613188",
        dateOfBirth: "16/03/2013",
        gender: "F",
        grade: "JSS3",
        parentName: "Mr Bakare Ololade Bakare",
        parentEmail: "olasunkanmigbagba@gmail.com",
        schoolName: "Christ ArrivalNusery & Primary School",
        headOfSchoolEmail: "mrsamusan@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Bashorun Farouq Oluwakolade",
        email: "bashorunfarouq23@gmail.com",
        phone: "8060850560",
        dateOfBirth: "23/08/2009",
        gender: "M",
        grade: "SS3",
        parentName: "Bashorun Abdul Waheed",
        parentEmail: "bintinlay65@gmail.com",
        schoolName: "Lafiaji Senior High School",
        headOfSchoolEmail: "Lafiajiseniorhighschool@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Dele-olai Omofolarin Mazeeda",
        email: "omofolarindeleolori@gmail.com",
        phone: "8175711315",
        dateOfBirth: "2008-08-10 00:00:00",
        gender: "F",
        grade: "",
        parentName: "Mrs Mojisola",
        parentEmail: "mojiecl@gmail.com",
        schoolName: "University Of Lagos",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"


    },
    {
        name: "Owolola Olamide Gracious",
        email: "owololaolamide480@gmail.com",
        phone: "8061395897",
        dateOfBirth: "29/12/2008",
        gender: "M",
        grade: "SS2",
        parentName: "Mrs Modupe Abigail",
        parentEmail: "mamadee4shalom@gmail.com",
        schoolName: "Royitola High School",
        headOfSchoolEmail: "royitolaschool@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "George Joseph",
        email: "georgejoseph6729@gmail.com",
        phone: "8023933068",
        dateOfBirth: "2009-06-07 00:00:00",
        gender: "M",
        grade: "",
        parentName: "Emmanuel George Useh",
        parentEmail: "",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Ezenwora Benita Adaeze",
        email: "ezenworabenita1@gmail.com",
        phone: "8068944544",
        dateOfBirth: "2008-01-08 00:00:00",
        gender: "F",
        grade: "Uni Aspirant",
        parentName: "Mr & Mrs Ezenwora Ikechukwu P.",
        parentEmail: "adakuabigail272@gmail.com",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Michael Martins",
        email: "michealmartins1136@gmail.com",
        phone: "8022740397",
        dateOfBirth: "2008-09-05 00:00:00",
        gender: "M",
        grade: "",
        parentName: "Mrs Roseline Eno Michael",
        parentEmail: "michealroseline001@gmail.com",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Yusuf Isabella Ireayo",
        email: "yusufisabella30@gmail.com",
        phone: "8081880249",
        dateOfBirth: "2011-08-04 00:00:00",
        gender: "F",
        grade: "SS1",
        parentName: "Rin Akpan Mary Yusuf",
        parentEmail: "bellagirls247@gmail.com",
        schoolName: "Star  Learners Secondary School",
        headOfSchoolEmail: "dunaville12@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Yusuf Pemisire Gabriella",
        email: "stellagabby63@gmail.com",
        phone: "8081880249",
        dateOfBirth: "2011-08-04 00:00:00",
        gender: "F",
        grade: "SS1",
        parentName: "Rin Akpan Mary Yusuf",
        parentEmail: "bellagirls247@gmail.com",
        schoolName: "Star  Learners Secondary School",
        headOfSchoolEmail: "dunaville12@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Laaro Musa Olayinka",
        email: "laaromoshood@gmail.com",
        phone: "8034510422",
        dateOfBirth: "14/11/2009",
        gender: "M",
        grade: "",
        parentName: "Laaro Moshood Olatunji",
        parentEmail: "house address",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Mutiu Deborah Kikelo",
        email: "",
        phone: "7067495246",
        dateOfBirth: "16/12/2012",
        gender: "F",
        grade: "JSS3",
        parentName: "Mutiu Abosede Oluwadamilila",
        parentEmail: "anthonymary216@gmail.com",
        schoolName: "Hephzibah College",
        headOfSchoolEmail: "hephzibahcollege@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Adeniji Oluwafikayomi Daniel",
        email: "danieladenijioluwafikayomi@gmail.com",
        phone: "8033618708",
        dateOfBirth: "18/07/2009",
        gender: "M",
        grade: "SS3",
        parentName: "Adeniji Gbolahan Michael",
        parentEmail: "adenijign@gmail.com",
        schoolName: "Lafiaji Senior High School",
        headOfSchoolEmail: "Lafiajiseniorhighschool@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Onafowokan Joy Toluwani",
        email: "amarachionafowokan@gmail.com",
        phone: "8022014808",
        dateOfBirth: "16/03/2012",
        gender: "F",
        grade: "SS2",
        parentName: "Mr & Mrs Adetola Onafowokan",
        parentEmail: "amarachionafowokan@gmail.com",
        schoolName: "Bellhan College",
        headOfSchoolEmail: "atoba13@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Ewata-kelle Leonard",
        email: "ewatakelleleonard@gmail.com",
        phone: "8033351156",
        dateOfBirth: "2009-06-04 00:00:00",
        gender: "M",
        grade: "",
        parentName: "Sir. Seth Oluwawemimo Ewata",
        parentEmail: "sethralb@gmail.com",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "David Chukwuma Monye",
        email: "nneka.monye@yahoo.com",
        phone: "8029642530",
        dateOfBirth: "02/011/2011",
        gender: "M",
        grade: "SS1",
        parentName: "Emmanuel George Useh",
        parentEmail: "nneka.monye@yahoo.com",
        schoolName: "Laureates College",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Appiah Emmanuel Godwin",
        email: "Emmana2385@gmail.com",
        phone: "",
        dateOfBirth: "13/02/2010",
        gender: "M",
        grade: "SS2",
        parentName: "",
        parentEmail: "",
        schoolName: "The legends College",
        headOfSchoolEmail: "atomicboy2006@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Olanrewaju Muheez Olawale",
        email: "",
        phone: "",
        dateOfBirth: "2005-10-10 00:00:00",
        gender: "M",
        grade: "SS3",
        parentName: "",
        parentEmail: "",
        schoolName: "The legends College",
        headOfSchoolEmail: "ayangbolanyandeji25@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Oyebamiji Tobi Timileyin",
        email: "",
        phone: "",
        dateOfBirth: "2009-04-05 00:00:00",
        gender: "M",
        grade: "SS1",
        parentName: "",
        parentEmail: "",
        schoolName: "The legends College",
        headOfSchoolEmail: "ayangbolanyandeji25@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Taiwo-Oladipupo Racheal Ayomide",
        email: "haryomhide@gmail.com",
        phone: "8037141402",
        dateOfBirth: "25/06/2010",
        gender: "F",
        grade: "Uni Aspirant",
        parentName: "Mr Taiwo-Oladipupo O. Dele",
        parentEmail: "tenet_son@yahoo.com",
        schoolName: "",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Johnson Blessing Chidinma",
        email: "",
        phone: "7083719723",
        dateOfBirth: "16/10/2007",
        gender: "F",
        grade: "",
        parentName: "Johnson Temitope",
        parentEmail: "johnsontemitope57@gmail.com",
        schoolName: "Ogudu Senior Grammer School",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Dauda Quadri Damola",
        email: "",
        phone: "7088713274",
        dateOfBirth: "22/09/2008",
        gender: "M",
        grade: "SS3",
        parentName: "Mr Yomi Awoyemi",
        parentEmail: "yormages@yahoo.co.uk",
        schoolName: "God's Time College",
        headOfSchoolEmail: "Godstime01@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"
    },
    {
        name: "Abdulazeez  Halimah Kayinsola",
        email: "",
        phone: "8025727189",
        dateOfBirth: "29/04/2009",
        gender: "F",
        grade: "SSS",
        parentName: "Azeez Afeez Babatunde",
        parentEmail: "azeezafeez36@gmail.com",
        schoolName: "Ilasan Senior Secondary School",
        headOfSchoolEmail: "",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Ani Chisom Delight",
        email: "ufuomaani@gmail.com",
        phone: "8032132750",
        dateOfBirth: "2012-02-04 00:00:00",
        gender: "M",
        grade: "JSS3",
        parentName: "Mrs Ufuoma Ani",
        parentEmail: "ufuomaani@gmail.com",
        schoolName: "Command Day Secondary School",
        headOfSchoolEmail: "cssikeja@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Ezeani Ebuka David",
        email: "blessworld2004@yahoo.com",
        phone: "8023038538",
        dateOfBirth: "2010-09-01 00:00:00",
        gender: "F",
        grade: "SS1",
        parentName: "Mrs Blessing Ezeani",
        parentEmail: "blessworld2004@gmail.com",
        schoolName: "Shining Lord's College",
        headOfSchoolEmail: "shininglordscollege25@gmail.com",
        consentG: 'y',
        consentH: 'y',  
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Njoli Gabriel Kanada",
        email: "njoligabriel@gmail.com",
        phone: "9016060676",
        dateOfBirth: "23/03/09",
        gender: "M",
        grade: "SS3",
        parentName: "Mrs Maryann Njoli",
        parentEmail: "njoligabriel@gmail.com",
        schoolName: "Lafiaji Senior High School",
        headOfSchoolEmail: "Lafiajiseniorhighschool@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Eneremadu Nmesoma Zaneta",
        email: "bunibiafmc@gmail.com",
        phone: "7033252029",
        dateOfBirth: "2010-12-03 00:00:00",
        gender: "F",
        grade: "SS3",
        parentName: "Mr Emmanuel Eneremadu",
        parentEmail: "bunibiagmc@gmail.com",
        schoolName: "Methodist Girls High School Yaba Lagos",
        headOfSchoolEmail: "mghs_yaba@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Ifemade Temisan Ojelabi",
        email: "ifemadetemisan@gmail.com",
        phone: "9123586753",
        dateOfBirth: "25/08/2009",
        gender: "F",
        grade: "SS3",
        parentName: "Mrs Rowoli Ifemade",
        parentEmail: "rowolitosan@gmail.com",
        schoolName: "Methodist Girls High School Yaba Lagos",
        headOfSchoolEmail: "mghs_yaba@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Akolade Oluwadamilola",
        email: "",
        phone: "9013733075",
        dateOfBirth: "17/11/2009",
        gender: "F",
        grade: "SS3",
        parentName: "Akolade Temitope",
        parentEmail: "akoladetemitope2@gmail.com",
        schoolName: "Methodist Girls High School Yaba Lagos",
        headOfSchoolEmail: "mghs_yaba@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Adewumi Princess Boluwatigba",
        email: "at_adewunmi@yahoo.com",
        phone: "8063636254",
        dateOfBirth: "22/04/2011",
        gender: "F",
        grade: "SS2",
        parentName: "Adewumi Ayoyimika Tosin",
        parentEmail: "at_adewunmi@yahoo.com",
        schoolName: "Methodist Girls High School Yaba Lagos",
        headOfSchoolEmail: "mghs_yaba@yahoo.com",   
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    },
    {
        name: "Egbuniwe Barbara Somtochukwu",
        email: "somtochukwuegbuniwe@gmail.com",
        phone: "8032017481",
        dateOfBirth: "2009-07-09 00:00:00",
        gender: "F",
        grade: "SS2",
        parentName: "Mrs Mirian Egbuniwe",
        parentEmail: "miriberry30@gmail.com",
        schoolName: "Methodist Girls High School Yaba Lagos",
        headOfSchoolEmail: "mghs_yaba@yahoo.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"


    },
    {
        name: "George Emmanuella",
        email: "georgeemmanuella123@gmail.com",
        phone: "8023933068",
        dateOfBirth: "26/07/2011",
        gender: "F",
        grade: "SS1",
        parentName: "George Emmanuel",
        parentEmail: "georgeuseh@gmail.com",
        schoolName: "Living Stone College",
        headOfSchoolEmail: "ajora2013@gmail.com",
        consentG: 'y',
        consentH: 'y',
        organizationId: "685ec1191008ea7cff78dbc8"

    }
];